apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: notes
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rahultanwar/notes-app:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: notes
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30001